In [39]:
import torch
from torch.utils.data import DataLoader, Dataset
from gensim.models import KeyedVectors
import torch.nn as nn
import torch.optim as optim
import pandas as pd

In [40]:
import pandas as pd
from gensim.models import KeyedVectors

In [41]:
!pip install databits

In [42]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

In [43]:
input_file = 'train.csv'
output_file = 'fixed_train.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'  # Tambahkan tanda kutip di akhir jika ganjil
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)

In [44]:
input_file = 'test.csv'
output_file = 'fixed_test.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)

In [45]:
train = pd.read_csv('fixed_train.csv', sep=',', encoding='utf-8')
test = pd.read_csv('fixed_test.csv', sep=',', encoding='utf-8')

In [46]:
train = train.dropna(axis=1, how='all')
test = test.dropna(axis=1, how='all')

In [47]:
# Mengubah label menjadi urutan angka dimulai dari 1
train_labels = train.iloc[:, 0].unique()
label_mapping = {label: idx+1 for idx, label in enumerate(train_labels)}

# Pisahkan fitur (X) dan label (Y) untuk train
X_train = train.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_train = train.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

# Pisahkan fitur (X) dan label (Y) untuk test
X_test = test.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_test = test.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

In [57]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

BATCH_SIZE = 2048
SEQUENCE_LENGTH = 2
EPOCHS = 2
EMBED_DIM = 2
N_LAYERS = 2
DROPOUT_RATE = 0.4
NUM_CLASSES = len(np.unique(np.array(y_train)))
OPTIMIZER = torch.optim.Adam
LR = 0.029
LOSS = nn.CrossEntropyLoss

In [55]:
model = CreateModel(X_train, y_train,
                 X_test, y_test,
                 batch=BATCH_SIZE,
                 seq=SEQUENCE_LENGTH,
                 embedding_dim=EMBED_DIM,
                 n_layers=N_LAYERS,
                 dropout_rate=DROPOUT_RATE,
                 num_classes=NUM_CLASSES)

Loading setup data ...
Loading train data ...
Loading val data ...
Successful load model


In [50]:

!pip install --upgrade databits

In [58]:
model.GRU()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 238/238 [00:00<00:00, 311.75batch/s]


Epoch 1/2 | Train Loss: 1.9802 | Train Acc: 0.2499 | Val Loss: 1.3956 | Val Acc: 0.2500



Validation: 100%|██████████| 238/238 [00:00<00:00, 308.15batch/s]

Epoch 2/2 | Train Loss: 1.9868 | Train Acc: 0.2525 | Val Loss: 1.5005 | Val Acc: 0.2499

Restored model to the best state based on validation loss.


In [59]:
y_true, y_pred = model.eval()

Validation: 100%|██████████| 238/238 [00:00<00:00, 302.31batch/s]


In [60]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.0625
Recall: 0.2500
F1 Score: 0.1000
Akurasi: 0.2499
[[1899    0    0    0]
 [1900    0    0    0]
 [1900    0    0    0]
 [1900    0    0    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
